Repository stolostron/observatorium-operator, pull requests merged in 2025-04, with the labels that each got.

#284 [release-2.12] Bump x/crypto to v0.36.0 & x/oauth2 to v0.28.0
  go.mod
  go.sum
Labels: lgtm

#285 [release-2.10] Bump x/crypto to v0.36.0 & x/oauth2 to v0.28.0
  go.mod
  go.sum
Labels: lgtm

#287 Add new SAST tasks to Konflux pipelines
  .tekton/observatorium-operator-acm-214-pull-request.yaml
  .tekton/observatorium-operator-acm-214-push.yaml
Labels: approved, lgtm, ok-to-test

#298 Update renovate.json
  renovate.json
Labels: approved, lgtm
