Repository stolostron/observatorium-operator, pull requests merged in 2025-01, with the labels that each got.

#219 Bump go x/net and x/crypto
  go.mod
  go.sum
Labels: approved, lgtm

#220 Bump go x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm

#227 chore: Enable hermetic builds
  .tekton/observatorium-operator-acm-213-pull-request.yaml
  .tekton/observatorium-operator-acm-213-push.yaml
Labels: approved, lgtm

#229 Update locutus to pick up x/net and x/crypto fix
  Containerfile.operator
  Dockerfile
Labels: approved, lgtm

#231 [release-2.9] Update locutus to pick up x/net and x/crypto fix
  Dockerfile
Labels: approved

#242 Update renovate.json
  renovate.json
Labels: approved, lgtm
